export const ELEMENTS = {
  // Mapeamentos de elementos de Criaç+ao do Anuncio
  //Logo da pagina do Meu Anuncio
  logo: '.nuxt-link-active > .logo',
  // pagina home
  fraseTopoHome: '.headline',
  botaoVenderVeiculo: '.tabs > :nth-child(2) > a',
  //Pagina de Anunciar
  planos: '.plans-list',
  planoStarter: '.plans-list > :nth-child(1) > .button',
  // Passo um criação do anuncio
  passoUmAtivo: '.step-one-active',
  acessorios: '.accessories',
  inputPlaca: '.licensing-plate > div > input',
  inputMarca: '#dropdown-brand > .input > input',
  inputModelo: '#dropdown-model > .input > input',
  inputVersao: '#dropdown-version > .input > input',
  inputAnoF: '#dropdown-manufactureYear > .input >input',
  inputAnoM: '#dropdown-modelYear > .input > input',
  inputKm: '.mileage > input',
  inputCombustivel: '#dropdown-fuel > .input > input',
  inputCambio: '#dropdown-gear > .input > input',
  inputCor: '#dropdown-color > .input > input',
  inputPorta: '#dropdown-doors > .input > input',
  inputBanco: '#dropdown-seats > .input > input',
  inputEstado: '#dropdown-region > .input > input',
  inputCidade: '#dropdown-city > .input > input',
  inputBuscaAcessorios: '.filter > input',
  dropdownInput: '.autocomplete',
  selectMarca: '.autocomplete > :nth-child(3)',
  selectModelo: '.autocomplete > :nth-child(3)',
  selectVersao: '.autocomplete > :nth-child(1)',
  selectAnoF: '.autocomplete > :nth-child(5)',
  selectAnoM: '.autocomplete > :nth-child(1)',
  selectCombustivel: '.autocomplete > :nth-child(4)',
  selectCambio: '.autocomplete > :nth-child(1) > :nth-child(3)',
  selectCor: '.orange',
  selectPorta: '.autocomplete > :nth-child(3)',
  selectBanco: '.autocomplete > :nth-child(2)',
  selectEstado: '.autocomplete > :nth-child(18)',
  selectCidade: '.autocomplete > :nth-child(221)',
  checkAcessoriosCompleto: '#accessories\\[\\]-0',
  checkAcessorioBuscado: '#accessories\\[\\]-83',
  botaoProximo: '#nextBtn',
  // Passo dois criação do anuncio
  passoDoisAtivo: '.step-two-active',
  inputValor: '.v-money',
  inputDescricao: 'textarea',
  // Passo três criação do anuncio
  passoTresAtivo: '.step-three-active',
  botãoTutorialImagens: '.reorganize-tutorial-info > .button',
  uploadImagens: '#uploader',
  LoadingBotãoImagem: '.spinner',
  // Passo quatro criação do anuncio
  passoQuatroAtivo: '.step-four-active',
  uploadRG: '.docs-step1',
  // Passo cinco criação do anuncio
  passoCincoAtivo: '.step-five-active',
  botaoRemoverImagem: '.docs-step3 > .send > [data-v-582ac574=""][data-v-28adcd4c=""] > .uploaded > .uploaded-photo > .remove-photo',
  selecionaBoleto: '.boleto',
  formDadosBoleto: ':nth-child(1) > .boleto-form',
  inputNome: '#boleto-name',
  inputRua: '#boleto-street',
  inputNumero: '#boleto-number',
  inputBairro: '#boleto-neighborhood',
  inputCep: '#boleto-cep',
  inputCidadeBoleto: '#boleto-city',
  inputEstadoBoleto: ':nth-child(1) > .boleto-form > :nth-child(4) > :nth-child(2) > #dropdown-uf > .input > input',
  selectEstadoBoleto: ':nth-child(1) > .boleto-form > :nth-child(4) > :nth-child(2) > #dropdown-uf > .autocomplete > :nth-child(16)',
  inputCpf: '#boleto-cpf',
  inputDtNasc: '#boleto-birth',
  inputEmail: '#boleto-email',
  inputFone: '#boleto-phone',
  botaoConcluir: '#onComplete'
};
